import React, { useState, useEffect } from "react";
import { X, Save, ChevronRight, ChevronLeft, Check } from "lucide-react";
import { questionSetService } from "../../services/questionSetService";
import { positionService } from "../../services/positionService";

const QuestionSetForm = ({ positionId, questionSet, onClose, onSuccess }) => {
  const [currentStep, setCurrentStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [positions, setPositions] = useState([]);
  
  const [formData, setFormData] = useState({
    questionSetCode: "", // Will be auto-generated by backend
    positionId: positionId || "",
    totalQuestions: "",
    totalDuration: 60, // Default duration: 60 minutes
    instruction: `Welcome to the Interview Assessment

Please follow these guidelines carefully:

1. READ EACH QUESTION THOROUGHLY
   - Take your time to understand what is being asked
   - Pay attention to all details and requirements

2. PROVIDE COMPREHENSIVE ANSWERS
   - Answer all questions to the best of your ability
   - Be clear, concise, and specific in your responses
   - Use examples from your experience when relevant

3. TIME MANAGEMENT
   - Manage your time wisely across all sections
   - Ensure you complete all questions within the allocated time
   - Review your answers before submitting

4. TECHNICAL REQUIREMENTS
   - Ensure you have a stable internet connection
   - Use a modern browser for the best experience
   - Save your work periodically

5. SUBMISSION
   - Double-check all your answers before final submission
   - Once submitted, you cannot make changes
   - Contact support if you encounter any technical issues

Good luck with your assessment!`, // Static default instruction template
    interviewPlatform: "",
    interviewMode: "",
    version: 1,
    complexityLevel: "", // Will be set by backend (default: MEDIUM)
    generalQuestionsCount: "",
    positionSpecificQuestionsCount: "",
    codingQuestionsCount: "",
    aptitudeQuestionsCount: "",
    status: "DRAFT", // Will be set by backend
    isActive: true,
    questionSectionIds: ""
  });

  useEffect(() => {
    // Load positions if positionId is not provided
    if (!positionId) {
      loadPositions();
    }
  }, [positionId]);

  useEffect(() => {
    if (questionSet) {
      const defaultInstruction = `Welcome to the Interview Assessment

Please follow these guidelines carefully:

1. READ EACH QUESTION THOROUGHLY
   - Take your time to understand what is being asked
   - Pay attention to all details and requirements

2. PROVIDE COMPREHENSIVE ANSWERS
   - Answer all questions to the best of your ability
   - Be clear, concise, and specific in your responses
   - Use examples from your experience when relevant

3. TIME MANAGEMENT
   - Manage your time wisely across all sections
   - Ensure you complete all questions within the allocated time
   - Review your answers before submitting

4. TECHNICAL REQUIREMENTS
   - Ensure you have a stable internet connection
   - Use a modern browser for the best experience
   - Save your work periodically

5. SUBMISSION
   - Double-check all your answers before final submission
   - Once submitted, you cannot make changes
   - Contact support if you encounter any technical issues

Good luck with your assessment!`;
      
      setFormData({
        questionSetCode: questionSet.questionSetCode || "",
        positionId: questionSet.positionId || positionId || "",
        totalQuestions: questionSet.totalQuestions || "",
        totalDuration: questionSet.totalDuration || 60,
        instruction: questionSet.instruction || defaultInstruction,
        interviewPlatform: questionSet.interviewPlatform || "",
        interviewMode: questionSet.interviewMode || "",
        version: questionSet.version || 1,
        complexityLevel: questionSet.complexityLevel || "",
        generalQuestionsCount: questionSet.generalQuestionsCount || "",
        positionSpecificQuestionsCount: questionSet.positionSpecificQuestionsCount || "",
        codingQuestionsCount: questionSet.codingQuestionsCount || "",
        aptitudeQuestionsCount: questionSet.aptitudeQuestionsCount || "",
        status: questionSet.status || "DRAFT",
        isActive: questionSet.isActive !== undefined ? questionSet.isActive : true,
        questionSectionIds: questionSet.questionSectionIds || ""
      });
    }
  }, [questionSet, positionId]);

  const loadPositions = async () => {
    try {
      const positionsData = await positionService.getAllPositions();
      setPositions(positionsData);
    } catch (error) {
      console.error("Error loading positions:", error);
    }
  };

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value
    }));
  };

  const handleNext = () => {
    if (currentStep < 5) {
      setCurrentStep(currentStep + 1);
    }
  };

  const handlePrevious = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1);
    }
  };

  const calculateTotalQuestions = () => {
    const general = parseInt(formData.generalQuestionsCount) || 0;
    const position = parseInt(formData.positionSpecificQuestionsCount) || 0;
    const coding = parseInt(formData.codingQuestionsCount) || 0;
    const aptitude = parseInt(formData.aptitudeQuestionsCount) || 0;
    return general + position + coding + aptitude;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Validate position is selected if not provided via prop
    if (!positionId && !formData.positionId) {
      alert("Please select a position");
      return;
    }

    setLoading(true);

    try {
      const totalQuestions = calculateTotalQuestions();
      // Calculate total duration based on rounds
      const general = parseInt(formData.generalQuestionsCount) || 0;
      const position = parseInt(formData.positionSpecificQuestionsCount) || 0;
      const coding = parseInt(formData.codingQuestionsCount) || 0;
      const aptitude = parseInt(formData.aptitudeQuestionsCount) || 0;
      const calculatedDuration = (general * 2) + (position * 3) + (coding * 10) + (aptitude * 2);
      const finalDuration = calculatedDuration > 0 ? calculatedDuration : 60;

      const questionSetData = {
        ...formData,
        positionId: positionId || formData.positionId,
        // Don't send questionSetCode if creating new (backend will auto-generate)
        questionSetCode: questionSet ? formData.questionSetCode : undefined,
        totalQuestions: formData.totalQuestions ? parseInt(formData.totalQuestions) : totalQuestions,
        totalDuration: finalDuration, // Auto-calculated based on rounds
        instruction: formData.instruction || `Welcome to the Interview Assessment

Please follow these guidelines carefully:

1. READ EACH QUESTION THOROUGHLY
   - Take your time to understand what is being asked
   - Pay attention to all details and requirements

2. PROVIDE COMPREHENSIVE ANSWERS
   - Answer all questions to the best of your ability
   - Be clear, concise, and specific in your responses
   - Use examples from your experience when relevant

3. TIME MANAGEMENT
   - Manage your time wisely across all sections
   - Ensure you complete all questions within the allocated time
   - Review your answers before submitting

4. TECHNICAL REQUIREMENTS
   - Ensure you have a stable internet connection
   - Use a modern browser for the best experience
   - Save your work periodically

5. SUBMISSION
   - Double-check all your answers before final submission
   - Once submitted, you cannot make changes
   - Contact support if you encounter any technical issues

Good luck with your assessment!`,
        version: parseInt(formData.version) || 1,
        generalQuestionsCount: formData.generalQuestionsCount ? parseInt(formData.generalQuestionsCount) : null,
        positionSpecificQuestionsCount: formData.positionSpecificQuestionsCount ? parseInt(formData.positionSpecificQuestionsCount) : null,
        codingQuestionsCount: formData.codingQuestionsCount ? parseInt(formData.codingQuestionsCount) : null,
        aptitudeQuestionsCount: formData.aptitudeQuestionsCount ? parseInt(formData.aptitudeQuestionsCount) : null,
        isActive: formData.isActive
      };

      let savedQuestionSet;
      if (questionSet) {
        savedQuestionSet = await questionSetService.updateQuestionSet(questionSet.id, questionSetData);
      } else {
        savedQuestionSet = await questionSetService.createQuestionSet(questionSetData);
      }

      alert(questionSet ? "Question set updated successfully!" : "Question set created successfully!");
      if (onSuccess) {
        onSuccess(savedQuestionSet);
      }
      onClose();
    } catch (error) {
      console.error("Error saving question set:", error);
      alert("Failed to save question set. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const steps = [
    { number: 1, name: "Basic Info", icon: "📋" },
    { number: 2, name: "General Questions", icon: "❓" },
    { number: 3, name: "Position Specific", icon: "💼" },
    { number: 4, name: "Coding", icon: "💻" },
    { number: 5, name: "Aptitude", icon: "🧮" }
  ];

  const renderStepContent = () => {
    switch (currentStep) {
      case 1: // General
        return (
          <div className="space-y-4">
            {!positionId && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Position *
                </label>
                <select
                  name="positionId"
                  value={formData.positionId}
                  onChange={handleChange}
                  required
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
                >
                  <option value="">Select a position</option>
                  {positions.map((position) => (
                    <option key={position.id} value={position.id}>
                      {position.code} - {position.title}
                    </option>
                  ))}
                </select>
              </div>
            )}

            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-sm font-medium text-gray-700">Total Duration:</span>
                <span className="text-sm font-semibold text-navy-900">
                  {(() => {
                    const general = parseInt(formData.generalQuestionsCount) || 0;
                    const position = parseInt(formData.positionSpecificQuestionsCount) || 0;
                    const coding = parseInt(formData.codingQuestionsCount) || 0;
                    const aptitude = parseInt(formData.aptitudeQuestionsCount) || 0;
                    const calculated = (general * 2) + (position * 3) + (coding * 10) + (aptitude * 2);
                    return calculated > 0 ? calculated : 60;
                  })()} minutes
                </span>
              </div>
              <div className="text-xs text-gray-500">
                Auto-calculated based on rounds: General (2 min/q), Position (3 min/q), Coding (10 min/q), Aptitude (2 min/q)
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Instructions
              </label>
              <textarea
                name="instruction"
                value={formData.instruction}
                onChange={handleChange}
                rows="4"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
                placeholder="Enter instructions for candidates..."
              />
              <p className="text-xs text-gray-500 mt-1">
                Default instructions are pre-filled, but you can edit them
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Interview Platform
              </label>
              <select
                name="interviewPlatform"
                value={formData.interviewPlatform}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
              >
                <option value="">Select platform</option>
                <option value="BROWSER">Browser</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Interview Mode
              </label>
              <select
                name="interviewMode"
                value={formData.interviewMode}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
              >
                <option value="">Select mode</option>
                <option value="CONVERSATIONAL">Conversational</option>
                <option value="NON_CONVERSATIONAL">Non-Conversational</option>
              </select>
            </div>


            <div className="flex items-center">
              <input
                type="checkbox"
                name="isActive"
                checked={formData.isActive}
                onChange={handleChange}
                className="mr-2"
              />
              <label className="text-sm font-medium text-gray-700">
                Active
              </label>
            </div>
          </div>
        );

      case 2: // General Questions
        return (
          <div className="space-y-4">
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
              <h3 className="text-lg font-semibold text-yellow-900 mb-2">
                General Questions
              </h3>
              <p className="text-sm text-yellow-700">
                General interview questions applicable to all candidates.
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Number of General Questions
              </label>
              <input
                type="number"
                name="generalQuestionsCount"
                value={formData.generalQuestionsCount}
                onChange={handleChange}
                min="0"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
                placeholder="e.g., 10"
              />
            </div>
          </div>
        );

      case 3: // Position Specific
        return (
          <div className="space-y-4">
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <h3 className="text-lg font-semibold text-blue-900 mb-2">
                Position Specific Questions
              </h3>
              <p className="text-sm text-blue-700">
                Questions tailored specifically for this position role and requirements.
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Number of Position Specific Questions
              </label>
              <input
                type="number"
                name="positionSpecificQuestionsCount"
                value={formData.positionSpecificQuestionsCount}
                onChange={handleChange}
                min="0"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
                placeholder="e.g., 5"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Question Section IDs (comma-separated or JSON array)
              </label>
              <textarea
                name="questionSectionIds"
                value={formData.questionSectionIds}
                onChange={handleChange}
                rows="3"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
                placeholder='e.g., ["section1", "section2"] or section1,section2'
              />
            </div>
          </div>
        );

      case 4: // Coding
        return (
          <div className="space-y-4">
            <div className="bg-green-50 border border-green-200 rounded-lg p-4">
              <h3 className="text-lg font-semibold text-green-900 mb-2">
                Coding Questions
              </h3>
              <p className="text-sm text-green-700">
                Programming and technical coding questions for the interview.
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Number of Coding Questions
              </label>
              <input
                type="number"
                name="codingQuestionsCount"
                value={formData.codingQuestionsCount}
                onChange={handleChange}
                min="0"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
                placeholder="e.g., 3"
              />
            </div>
          </div>
        );

      case 5: // Aptitude
        return (
          <div className="space-y-4">
            <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
              <h3 className="text-lg font-semibold text-purple-900 mb-2">
                Aptitude Questions
              </h3>
              <p className="text-sm text-purple-700">
                Logical reasoning and aptitude questions.
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Number of Aptitude Questions
              </label>
              <input
                type="number"
                name="aptitudeQuestionsCount"
                value={formData.aptitudeQuestionsCount}
                onChange={handleChange}
                min="0"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
                placeholder="e.g., 5"
              />
            </div>

            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
              <h4 className="text-sm font-semibold text-gray-900 mb-2">
                Total Questions Summary
              </h4>
              <div className="space-y-1 text-sm">
                <div className="flex justify-between">
                  <span>General Questions:</span>
                  <span className="font-medium">{formData.generalQuestionsCount || 0}</span>
                </div>
                <div className="flex justify-between">
                  <span>Position Specific:</span>
                  <span className="font-medium">{formData.positionSpecificQuestionsCount || 0}</span>
                </div>
                <div className="flex justify-between">
                  <span>Coding Questions:</span>
                  <span className="font-medium">{formData.codingQuestionsCount || 0}</span>
                </div>
                <div className="flex justify-between">
                  <span>Aptitude Questions:</span>
                  <span className="font-medium">{formData.aptitudeQuestionsCount || 0}</span>
                </div>
                <div className="flex justify-between pt-2 border-t border-gray-300">
                  <span className="font-semibold">Total:</span>
                  <span className="font-bold text-navy-900">{calculateTotalQuestions()}</span>
                </div>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Total Questions (auto-calculated or override)
              </label>
              <input
                type="number"
                name="totalQuestions"
                value={formData.totalQuestions || calculateTotalQuestions()}
                onChange={handleChange}
                min="0"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
                placeholder="Auto-calculated"
              />
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex justify-between items-center">
          <h2 className="text-2xl font-bold text-navy-900">
            {questionSet ? "Edit Question Set" : "Create Question Set"}
          </h2>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600"
          >
            <X size={24} />
          </button>
        </div>

        {/* Step Indicator */}
        <div className="px-6 py-4 border-b border-gray-200">
          <div className="flex items-center justify-between">
            {steps.map((step, index) => (
              <React.Fragment key={step.number}>
                <div className="flex items-center">
                  <div
                    className={`flex items-center justify-center w-10 h-10 rounded-full border-2 ${
                      currentStep === step.number
                        ? "bg-navy-900 text-white border-navy-900"
                        : currentStep > step.number
                        ? "bg-green-500 text-white border-green-500"
                        : "bg-white text-gray-400 border-gray-300"
                    }`}
                  >
                    {currentStep > step.number ? (
                      <Check size={20} />
                    ) : (
                      <span className="text-sm font-semibold">{step.number}</span>
                    )}
                  </div>
                  <div className="ml-2 hidden sm:block">
                    <div className={`text-sm font-medium ${
                      currentStep === step.number ? "text-navy-900" : "text-gray-500"
                    }`}>
                      {step.name}
                    </div>
                  </div>
                </div>
                {index < steps.length - 1 && (
                  <div className={`flex-1 h-0.5 mx-2 ${
                    currentStep > step.number ? "bg-green-500" : "bg-gray-300"
                  }`} />
                )}
              </React.Fragment>
            ))}
          </div>
        </div>

        <form onSubmit={handleSubmit} className="p-6">
          {renderStepContent()}

          <div className="flex justify-between gap-3 pt-6 mt-6 border-t">
            <button
              type="button"
              onClick={handlePrevious}
              disabled={currentStep === 1}
              className={`px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 flex items-center gap-2 ${
                currentStep === 1 ? "opacity-50 cursor-not-allowed" : ""
              }`}
            >
              <ChevronLeft size={18} />
              Previous
            </button>

            <div className="flex gap-3">
              <button
                type="button"
                onClick={onClose}
                className="px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
              >
                Cancel
              </button>
              {currentStep < 5 ? (
                <button
                  type="button"
                  onClick={handleNext}
                  className="px-6 py-2 bg-navy-900 text-white rounded-lg hover:bg-navy-800 flex items-center gap-2"
                >
                  Next
                  <ChevronRight size={18} />
                </button>
              ) : (
                <button
                  type="submit"
                  disabled={loading}
                  className="px-6 py-2 bg-navy-900 text-white rounded-lg hover:bg-navy-800 flex items-center gap-2 disabled:opacity-50"
                >
                  <Save size={18} />
                  {loading ? "Saving..." : questionSet ? "Update" : "Create"}
                </button>
              )}
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};

export default QuestionSetForm;

