import React, { useState, useEffect } from "react";
import { X, Save, Upload, FileText, Download, Trash2 } from "lucide-react";
import { positionService } from "../../services/positionService";
import { fileService } from "../../services/fileService";
import { AI_BACKEND_WS_URL } from "../../constants/api";
import QuestionSetForm from "../questionSets/QuestionSetForm";

const PositionForm = ({ position, positionTitles: propPositionTitles, onClose }) => {
  const [formData, setFormData] = useState({
    code: "", // Will be auto-generated by backend
    title: "",
    domainType: "",
    minimumExperience: "",
    maximumExperience: "",
    jdDocumentPath: "",
    jdDocumentFileName: "",
    positionStatus: "ACTIVE", // Default to ACTIVE
    noOfPositions: "",
    expectedStartDate: "", // Will be auto-set to today by backend
    applicationDeadline: "",
    internalNotes: "", // Will be removed from form but kept in backend
    mandatorySkills: [],
    optionalSkills: []
  });
  const [positionTitles, setPositionTitles] = useState(propPositionTitles || []);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [selectedFile, setSelectedFile] = useState(null);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [skillInput, setSkillInput] = useState({ mandatory: "", optional: "" });
  const [showQuestionSetForm, setShowQuestionSetForm] = useState(false);
  const [createdPositionId, setCreatedPositionId] = useState(null);
  const [isGeneratingSkills, setIsGeneratingSkills] = useState(false);

  // Load position titles when form opens (only if not provided as prop)
  useEffect(() => {
    const loadTitles = async () => {
      if (!propPositionTitles || propPositionTitles.length === 0) {
        try {
          const titles = await positionService.getAllPositionTitles();
          setPositionTitles(titles);
        } catch (error) {
          console.error("Error loading position titles:", error);
        }
      } else {
        setPositionTitles(propPositionTitles);
      }
    };
    loadTitles();
  }, [propPositionTitles]);

  useEffect(() => {
    if (position) {
      setFormData({
        code: position.code || "",
        title: position.title || "",
        domainType: position.domainType || "",
        minimumExperience: position.minimumExperience || "",
        maximumExperience: position.maximumExperience || "",
        jdDocumentPath: position.jdDocumentPath || "",
        jdDocumentFileName: position.jdDocumentFileName || "",
        positionStatus: position.positionStatus || "DRAFT",
        noOfPositions: position.noOfPositions || "",
        expectedStartDate: position.expectedStartDate || "",
        applicationDeadline: position.applicationDeadline || "",
        internalNotes: position.internalNotes || "",
        mandatorySkills: position.mandatorySkills || [],
        optionalSkills: position.optionalSkills || []
      });
    }
  }, [position]);



  const handleGenerateSkills = async () => {
    if (!formData.title || !formData.domainType) {
      alert("Please fill Title and Domain Type first.");
      return;
    }

    setIsGeneratingSkills(true);
    let socket = null;

    try {
      socket = new WebSocket(`${AI_BACKEND_WS_URL}/ws/generate-skills`);

      socket.onopen = () => {
        console.log("AI Skills WebSocket connected");
        const payload = {
          title: formData.title,
          domain: formData.domainType,
          minExp: formData.minimumExperience ? parseInt(formData.minimumExperience) : 0,
          maxExp: formData.maximumExperience ? parseInt(formData.maximumExperience) : 0
        };
        socket.send(JSON.stringify(payload));
      };

      socket.onmessage = (event) => {
        const response = JSON.parse(event.data);
        if (response.success) {
          const newMandatory = response.mandatory || [];
          const newOptional = response.optional || [];

          // Merge unique skills
          setFormData(prev => ({
            ...prev,
            mandatorySkills: [...new Set([...prev.mandatorySkills, ...newMandatory])],
            optionalSkills: [...new Set([...prev.optionalSkills, ...newOptional])]
          }));

          alert("Skills generated successfully via AI!");
        } else {
          alert(response.error || "Failed to generate skills.");
        }
        socket.close();
      };

      socket.onerror = (error) => {
        console.error("WebSocket error:", error);
        alert("Connection to AI service failed.");
        setIsGeneratingSkills(false);
      };

      socket.onclose = () => {
        console.log("AI Skills WebSocket closed");
        setIsGeneratingSkills(false);
      };

    } catch (err) {
      console.error("Skill generation error:", err);
      alert("Failed to start skill generation process.");
      setIsGeneratingSkills(false);
      if (socket) socket.close();
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleAddSkill = (type) => {
    const skill = type === "mandatory" ? skillInput.mandatory : skillInput.optional;
    if (skill.trim()) {
      setFormData(prev => ({
        ...prev,
        [type === "mandatory" ? "mandatorySkills" : "optionalSkills"]: [
          ...prev[type === "mandatory" ? "mandatorySkills" : "optionalSkills"],
          skill.trim()
        ]
      }));
      setSkillInput(prev => ({ ...prev, [type]: "" }));
    }
  };

  const handleRemoveSkill = (type, index) => {
    setFormData(prev => {
      const skills = [...prev[type === "mandatory" ? "mandatorySkills" : "optionalSkills"]];
      skills.splice(index, 1);
      return { ...prev, [type === "mandatory" ? "mandatorySkills" : "optionalSkills"]: skills };
    });
  };

  const handleFileSelect = async (e) => {
    const file = e.target.files[0];
    if (!file) return;

    // Validate file type
    const allowedTypes = ["application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];
    if (!allowedTypes.includes(file.type)) {
      alert("Invalid file type. Please upload PDF, DOC, or DOCX files only.");
      return;
    }

    // Validate file size (10MB)
    if (file.size > 10 * 1024 * 1024) {
      alert("File size exceeds 10MB limit.");
      return;
    }

    setSelectedFile(file);
    setUploading(true);
    setUploadProgress(0);

    try {
      // Upload file first
      const uploadResponse = await fileService.uploadJdDocument(file);

      // Update form data with file path and name
      setFormData(prev => ({
        ...prev,
        jdDocumentPath: uploadResponse.filePath,
        jdDocumentFileName: uploadResponse.fileName
      }));

      setUploadProgress(100);
      alert("File uploaded successfully!");
    } catch (error) {
      console.error("Error uploading file:", error);
      alert(error.response?.data?.error || "Failed to upload file. Please try again.");
      setSelectedFile(null);
    } finally {
      setUploading(false);
      setUploadProgress(0);
      // Reset file input
      e.target.value = "";
    }
  };

  const handleRemoveFile = async () => {
    if (!formData.jdDocumentPath) return;

    // Extract subfolder and filename from path
    const pathParts = formData.jdDocumentPath.split("/");
    if (pathParts.length >= 2) {
      const subfolder = pathParts[0];
      const filename = pathParts.slice(1).join("/");

      try {
        await fileService.deleteFile(subfolder, filename);
        setFormData(prev => ({
          ...prev,
          jdDocumentPath: "",
          jdDocumentFileName: ""
        }));
        setSelectedFile(null);
        alert("File removed successfully!");
      } catch (error) {
        console.error("Error deleting file:", error);
        // Even if delete fails, clear from form
        setFormData(prev => ({
          ...prev,
          jdDocumentPath: "",
          jdDocumentFileName: ""
        }));
        setSelectedFile(null);
      }
    } else {
      // Just clear from form if path format is unexpected
      setFormData(prev => ({
        ...prev,
        jdDocumentPath: "",
        jdDocumentFileName: ""
      }));
      setSelectedFile(null);
    }
  };

  const handleDownloadFile = () => {
    if (!formData.jdDocumentPath) return;

    const pathParts = formData.jdDocumentPath.split("/");
    if (pathParts.length >= 2) {
      const subfolder = pathParts[0];
      const filename = pathParts.slice(1).join("/");
      const downloadUrl = fileService.getFileDownloadUrl(subfolder, filename);
      window.open(downloadUrl, "_blank");
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    try {
      const positionData = {
        // Don't send code if creating new (backend will auto-generate)
        code: position ? formData.code : undefined,
        title: formData.title,
        domainType: formData.domainType,
        minimumExperience: formData.minimumExperience ? parseInt(formData.minimumExperience) : null,
        maximumExperience: formData.maximumExperience ? parseInt(formData.maximumExperience) : null,
        jdDocumentPath: formData.jdDocumentPath,
        jdDocumentFileName: formData.jdDocumentFileName,
        positionStatus: formData.positionStatus || "ACTIVE",
        noOfPositions: formData.noOfPositions ? parseInt(formData.noOfPositions) : null,
        // Don't send expectedStartDate (backend will auto-set to today)
        expectedStartDate: position ? formData.expectedStartDate || null : undefined,
        applicationDeadline: formData.applicationDeadline || null,
        internalNotes: formData.internalNotes || null,
        mandatorySkills: formData.mandatorySkills,
        optionalSkills: formData.optionalSkills
      };

      let savedPosition;
      if (position) {
        savedPosition = await positionService.updatePosition(position.id, positionData);
      } else {
        savedPosition = await positionService.createPosition(positionData);
      }



      if (position) {
        alert("Position updated successfully!");
        onClose();
      } else {
        // For new positions, navigate to question set creation
        alert("Position created successfully! Now create question sets for this position.");
        setCreatedPositionId(savedPosition.id);
        setShowQuestionSetForm(true);
      }
    } catch (error) {
      console.error("Error saving position:", error);
      alert("Failed to save position. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex justify-between items-center">
          <h2 className="text-2xl font-bold text-navy-900">
            {position ? "Edit Position" : "Create Position"}
          </h2>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600"
          >
            <X size={24} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Title *
              </label>
              <select
                name="title"
                value={formData.title}
                onChange={handleChange}
                required
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
              >
                <option value="">Select a title</option>
                {positionTitles && positionTitles.length > 0 ? (
                  positionTitles.map((title) => (
                    <option key={title.id} value={title.title}>
                      {title.title}
                    </option>
                  ))
                ) : (
                  <option value="" disabled>No titles available. Please create titles first.</option>
                )}
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Domain Type
              </label>
              <select
                name="domainType"
                value={formData.domainType}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
              >
                <option value="">Select domain type</option>
                <option value="TECH">TECH</option>
                <option value="NON TECH">NON TECH</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Status
              </label>
              <select
                name="positionStatus"
                value={formData.positionStatus}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
              >
                <option value="ACTIVE">Active</option>
                <option value="DRAFT">Draft</option>
                <option value="CLOSED">Closed</option>
                <option value="CANCELLED">Cancelled</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Minimum Experience (years)
              </label>
              <input
                type="number"
                name="minimumExperience"
                value={formData.minimumExperience}
                onChange={handleChange}
                min="0"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Maximum Experience (years)
              </label>
              <input
                type="number"
                name="maximumExperience"
                value={formData.maximumExperience}
                onChange={handleChange}
                min="0"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Number of Positions
              </label>
              <input
                type="number"
                name="noOfPositions"
                value={formData.noOfPositions}
                onChange={handleChange}
                min="1"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Application Deadline (Optional)
              </label>
              <input
                type="date"
                name="applicationDeadline"
                value={formData.applicationDeadline}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
              />
              <p className="text-xs text-gray-500 mt-1">
                Expected Start Date will be automatically set to today
              </p>
            </div>

            <div className="col-span-2">
              <button
                type="button"
                onClick={handleGenerateSkills}
                disabled={isGeneratingSkills}
                className="px-4 py-2 bg-qwikBlue text-white rounded-lg hover:bg-qwikBlueDark disabled:opacity-50 flex items-center gap-2 text-sm transition-colors"
              >
                {isGeneratingSkills ? (
                  <div className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                ) : null}
                Generate AI Skills
              </button>
            </div>

            {/* JD Document Upload - Full Width */}
            <div className="col-span-2">
              <label className="block text-sm font-medium text-gray-700 mb-2">
                JD Document (PDF, DOC, DOCX - Max 10MB)
              </label>

              {!formData.jdDocumentPath ? (
                <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center hover:border-navy-500 transition-colors">
                  <input
                    type="file"
                    id="jd-document-upload"
                    accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                    onChange={handleFileSelect}
                    disabled={uploading}
                    className="hidden"
                  />
                  <label
                    htmlFor="jd-document-upload"
                    className={`cursor-pointer flex flex-col items-center gap-2 ${uploading ? "opacity-50 cursor-not-allowed" : ""}`}
                  >
                    <Upload size={32} className="text-gray-400" />
                    <span className="text-sm text-gray-600">
                      {uploading ? "Uploading..." : "Click to upload or drag and drop"}
                    </span>
                    {uploading && (
                      <div className="w-full max-w-xs mx-auto">
                        <div className="bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-navy-900 h-2 rounded-full transition-all duration-300"
                            style={{ width: `${uploadProgress}%` }}
                          ></div>
                        </div>
                      </div>
                    )}
                  </label>
                </div>
              ) : (
                <div className="border border-gray-300 rounded-lg p-4 bg-gray-50">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <FileText size={24} className="text-navy-900" />
                      <div>
                        <p className="text-sm font-medium text-gray-900">
                          {formData.jdDocumentFileName || "Document"}
                        </p>
                        <p className="text-xs text-gray-500">
                          {formData.jdDocumentPath}
                        </p>
                      </div>
                    </div>
                    <div className="flex gap-2">
                      <button
                        type="button"
                        onClick={handleDownloadFile}
                        className="p-2 text-navy-600 hover:text-navy-900 hover:bg-navy-100 rounded-lg transition-colors"
                        title="Download"
                      >
                        <Download size={20} />
                      </button>
                      <button
                        type="button"
                        onClick={handleRemoveFile}
                        className="p-2 text-red-600 hover:text-red-900 hover:bg-red-100 rounded-lg transition-colors"
                        title="Remove"
                      >
                        <Trash2 size={20} />
                      </button>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Mandatory Skills */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Mandatory Skills
            </label>
            <div className="mb-2">
              <input
                type="text"
                value={skillInput.mandatory}
                onChange={(e) => setSkillInput(prev => ({ ...prev, mandatory: e.target.value }))}
                onKeyPress={(e) => e.key === "Enter" && (e.preventDefault(), handleAddSkill("mandatory"))}
                placeholder="Enter skill and press Enter"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
              />
            </div>
            <div className="flex flex-wrap gap-2">
              {formData.mandatorySkills.map((skill, index) => (
                <span
                  key={index}
                  className="px-3 py-1 bg-red-100 text-red-800 rounded-full text-sm flex items-center gap-2"
                >
                  {skill}
                  <button
                    type="button"
                    onClick={() => handleRemoveSkill("mandatory", index)}
                    className="text-red-600 hover:text-red-800"
                  >
                    ×
                  </button>
                </span>
              ))}
            </div>
          </div>

          {/* Optional Skills */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Optional Skills
            </label>
            <div className="flex gap-2 mb-2">
              <input
                type="text"
                value={skillInput.optional}
                onChange={(e) => setSkillInput(prev => ({ ...prev, optional: e.target.value }))}
                onKeyPress={(e) => e.key === "Enter" && (e.preventDefault(), handleAddSkill("optional"))}
                placeholder="Enter skill and press Enter"
                className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-navy-500"
              />
              <button
                type="button"
                onClick={() => handleAddSkill("optional")}
                className="px-4 py-2 bg-qwikBlue text-white rounded-lg hover:bg-qwikBlueDark transition-colors"
              >
                Add
              </button>
            </div>
            <div className="flex flex-wrap gap-2">
              {formData.optionalSkills.map((skill, index) => (
                <span
                  key={index}
                  className="px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm flex items-center gap-2"
                >
                  {skill}
                  <button
                    type="button"
                    onClick={() => handleRemoveSkill("optional", index)}
                    className="text-blue-600 hover:text-blue-800"
                  >
                    ×
                  </button>
                </span>
              ))}
            </div>
          </div>


          <div className="flex justify-end gap-3 pt-4 border-t">
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2 border border-gray-300 bg-white text-gray-700 hover:bg-gray-50 rounded-lg transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="px-6 py-2 bg-gradient-to-r from-blue-600 to-qwikBlue hover:from-blue-700 hover:to-qwikBlueDark text-white rounded-lg flex items-center gap-2 disabled:opacity-50 transition-all shadow-md"
            >
              <Save size={18} />
              {loading ? "Saving..." : position ? "Update" : "Create"}
            </button>
          </div>
        </form>
      </div>

      {/* Question Set Form Modal */}
      {showQuestionSetForm && createdPositionId && (
        <QuestionSetForm
          positionId={createdPositionId}
          onClose={() => {
            setShowQuestionSetForm(false);
            setCreatedPositionId(null);
            onClose();
          }}
          onSuccess={() => {
            setShowQuestionSetForm(false);
            setCreatedPositionId(null);
            onClose();
          }}
        />
      )}
    </div>
  );
};

export default PositionForm;

